n = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculas é: {}'.format(n.upper()))
print('Seu nome em minúsculas é: {}'.format(n.lower()))
print('Seu nome tem ao todo {} letras'.format(len(n.replace(" ", "")))) #Também poderia ser usado len(n) - nome.count('')
print('Seu primeiro nome é: {} e ele tem {} letras.'.format(n.split()[0], len(n.split()[0])))
